language: python
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get update
  - pip install -r requirements.txt --use-mirrors
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq python-scipy
  - sudo apt-get install -qq python-pandas
  - sudo pip install patsy --use-mirrors
  - sudo apt-get install statsmodels --use-mirrors
  - sudo apt-get install -qq msgpack-python
  - cp src/settings.py.example src/settings.py
script: "nosetests -v --nocapture"